
name: Build Electron App For Win/Mac

on:
  push:
    tags:
      - 'v*.*.*'

# Workflow's jobs
jobs:
  # job's id
  release:
    # job's name
    name: build and release electron app

    # the type of machine to run the job on
    runs-on: ${{ matrix.os }}

    # create a build matrix for jobs
    strategy:
      matrix:
        os: [windows-2019, macos-13.15.2]

    # create steps
    steps:
      # step1: check out repository
      - name: Check out git repository
        uses: actions/checkout@v2

      # step2: install node env
      - name: Install Node.js
        uses: actions/setup-node@v2-beta

      # step3: npm install
      - name: npm install
        run: |
          npm install

      # step4: build app for mac/win
      - name: build windows app
        if: matrix.os == 'windows-2019'
        run: |
          npm run build:win

      - name: build mac app
        if: matrix.os == 'macos-13.15.2'
        run: |
          npm run build:mac

      # step5: cleanup artifacts in dist_electron

      - name: List Release
        run: ls -l dist

      - name: Win Release file
        run: echo "dist/pense-${{ env.RELEASE_VERSION }}-setup.exe"

      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: false
          prerelease: false
          files: "dist/pense-${{ env.RELEASE_VERSION }}-setup.exe"
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
